import requests
from requests.exceptions import HTTPError

# List of players
players = [
    "JaloliddinIlkhomi",
    "Blitz-Warrior1993",
    "Sanan_Sjugirov",
    "Buffy7",
    "Sakanelli",
    "grzechu96",
    "FL0RIAN0P0LIS",
    "mbojan",
    "stollenmonster",
    "Topspin111",
    "Mykola-Bortnyk",
    "ArkadiyKhromaev777",
    "luffygear7",
    "Azeryahu",
    "mac0504",
    "IGROK1111",
    "Aqueen055",
    "tom740",
    "oknvs",
    "vi_pranav",
    "Salem-AR",
    "Bigfish1995",
    "SaqoChess_Coach",
    "Arystanner",
    "shimastream",
    "Oleksandr_Bortnyk",
    "BogdanDeac",
    "joppie2",
    "NikoTheodorou",
    "wonderfultime",
    "Zq1",  # This is causing the 404 error
    "ChessBrah",
    "DenLaz",
    "howitzer14",
    "RadoslawPsyk",
    "ChessWeebs",
    "Blitzstream",
    "alexrustemov",
    "GHANDEEVAM2003",
    "seramoral",
    "Grandmaster2B",
    "jlucasvf",
    "francyIM",
    "BigAl",
    "Legendinunknown",
    "severomorskij",
    "daika91",
    "ChessQueen",
    "Petrovic_Aleksa",
    "c63_amg",
    "ChessShop",
    "Orange_Ghost",
    "GMKrikor",
    "HSH1987",
    "larsmandreassen",
    "TheRealGmochey",
    "MokshAD1603",
    "eljanov",
    "Vladimir_Zakhartsov",
    "Vaibhavraut99",
    "AChucky",
    "1tsNowOrNever",
    "inneremptiness",
    "theexpertpatzer",
    "Kempsy",
    "TrahtarBelarus",
    "Twitch_ElhamBlitz05",
    "thatsallshewrote",
    "CMmauricio",
    "VitorBronson",
    "Aradhya2000",
    "Cayse",
    "Grandelicious",
    "TigrVShlyape",
    "biostatistician",
    "fm9714",
    "AlexPapasimakopoulos",
    "Arek_pacitan",
    "Vahe_Danielyan",
    "Msb2",
    "GMWSO",
    "daro94",
    "Hikaru",
    "Jospem",
    "Njal28",
    "Duhless",
    "Byniolus",
    "Konavets",
    "tptagain",
    "DetskiSad",
    "LyonBeast",
    "mishanick",
    "SantoBlue",
    "nihalsarin",
    "penguingm1",
    "rpragchess",
    "dropstoneDP",
    "AnthonyWirig",
    "TrimitziosP7",
    "vaishali2001",
    "WiniVidiVici",
    "MagnusCarlsen",
    "ManuDavid2910",
    "Semyon_Khanin",
    "VincentKeymer",
    "exoticprincess",
    "FabianoCaruana",
    "LacusSomniorum",
    "BrandonJacobson",
    "GukeshDommaraju",
    "DanielNaroditsky",
    "kirillshevchenko",
    "spicycaterpillar",
    "RaunakSadhwani2005",
]

def is_player_valid(username):
    url = f"https://api.chess.com/pub/player/{username}"
    try:
        response = requests.get(url)
        response.raise_for_status()  # Will raise HTTPError for bad responses
        return True
    except HTTPError as http_err:
        if response.status_code == 404:
            print(f"Player '{username}' not found (404). Skipping.")
        else:
            print(f"HTTP error occurred for '{username}': {http_err}")
    except Exception as err:
        print(f"An error occurred for '{username}': {err}")
    return False

# Filter valid players
valid_players = [player for player in players if is_player_valid(player)]
print(f"Total valid players: {len(valid_players)}")
